name: Build PDF
on: [push]
jobs:
  build_latex:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install mtp2lite fonts
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add file sudo coreutils
            wget https://mirrors.ctan.org/fonts/mtp2lite.zip
            wget https://raw.githubusercontent.com/jamespfennell/mathtime-installer/master/mtpro2-texlive.sh
            sed -i 's%${TEMPDIR}/texmf%${TEMPDIR}/mtp2lite/texmf%g' mtpro2-texlive.sh
            chmod +x ./mtpro2-texlive.sh
            ./mtpro2-texlive.sh -i mtp2lite.zip
            latexmk -pdf -file-line-error -halt-on-error -interaction=nonstopmode clrs4e-solutions.tex

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: clrs4e-solutions.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
