name: Build PDF
on: [push]
jobs:
  build_latex:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: clrs4e-solutions.tex

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: clrs4e-solutions.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
